apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-red-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team-red
  template:
    metadata:
      labels:
        app: team-red
    spec:
      containers:
      - name: team-red
        image: <ACR Name>.azurecr.io/team-red:v1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3003
